export const Assets = {
  cloud: require('../assets/cloud.png'),
  notificationIcon: require('../assets/notificationIcon.png'),
  bulb: require('../assets/bulb.png'),
  tv: require('../assets/tv.png'),
  fridge: require('../assets/fridge.png'),
  wifi: require('../assets/wifi.jpeg'),
  arrowIcon: require('../assets/arrow.png'),
  bellIcon: require('../assets/bell.png'),
  batteryIcon: require('../assets/battery_icon.png'),
  humidityIcon: require('../assets/humidity_icon.png'),
  gensetIcon: require('../assets/genset_icon.png'),
  waterIcon: require('../assets/water_icon.webp'),
  acIcon: require('../assets/ac_icon.png'),
  tempIcon: require('../assets/temp_icon.png'),
  mainSupplyIcon: require('../assets/main_supply_icon.png'),
  waterLowIcon: require('../assets/water_white_icon.png'),
  lowBatteryIcon: require('../assets/low_battery_icon.png'),
  deviceOffIcon: require('../assets/device_off_icon.png'),
  arrowIcon2: require('../assets/arrow_icon.png'),
  batterylistIcon: require('../assets/battery_list_icon.jpeg'),
  rightArrow: require('../assets/right_arrow.png'),
};
